/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rompecabezasio;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author marlon
 */
public class MenuInicio extends javax.swing.JFrame {

    /**
     * Creates new form MenuInicio
     */
    public MenuInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnJuego1 = new javax.swing.JButton();
        btnJuego2 = new javax.swing.JButton();
        btnJuego3 = new javax.swing.JButton();
        lblIO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RompeCabezas IO (Menu Principal)");
        setBackground(java.awt.Color.white);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        btnJuego1.setText("RompeCabezas (Matematicas)");
        btnJuego1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJuego1ActionPerformed(evt);
            }
        });

        btnJuego2.setText("RompeCabezas (Internet of Things)");
        btnJuego2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJuego2ActionPerformed(evt);
            }
        });

        btnJuego3.setText("RompeCabezas (BitCoin)");
        btnJuego3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJuego3ActionPerformed(evt);
            }
        });

        lblIO.setBackground(new java.awt.Color(255, 102, 51));
        lblIO.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblIO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIO.setText("INVESTIGACIÓN DE OPERACIONES");
        lblIO.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        lblIO.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnJuego3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnJuego1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnJuego2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblIO, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblIO, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnJuego1)
                .addGap(18, 18, 18)
                .addComponent(btnJuego2)
                .addGap(18, 18, 18)
                .addComponent(btnJuego3)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnJuego1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJuego1ActionPerformed
        JFrame frame1 = new JFrame("RompeCabezas Matematicas");
        Tablero canvas1 = new Tablero();
        canvas1.addFigura(new Pieza(834, 14, "/juego1/mate.jpg"));
        canvas1.addFigura(new Pieza(14, 370, "/juego1/mate1.jpg"));
        canvas1.addFigura(new Pieza(14, 14, "/juego1/mate2.jpg"));
        canvas1.addFigura(new Pieza(14, 475, "/juego1/mate3.jpg"));
        canvas1.addFigura(new Pieza(125, 219, "/juego1/mate4.jpg"));
        canvas1.addFigura(new Pieza(14, 266, "/juego1/mate5.jpg"));
        canvas1.addFigura(new Pieza(233, 220, "/juego1/mate6.jpg"));
        canvas1.addFigura(new Pieza(14, 581, "/juego1/mate7.jpg"));
        canvas1.addFigura(new Pieza(125, 166, "/juego1/mate8.jpg"));
        canvas1.addFigura(new Pieza(125, 14, "/juego1/mate9.jpg"));
        canvas1.addFigura(new Pieza(300, 14, "/juego1/mate10.jpg"));
        canvas1.addFigura(new Pieza(338, 118, "/juego1/mate11.jpg"));
        canvas1.addFigura(new Pieza(507, 14, "/juego1/mate12.jpg"));
        frame1.getContentPane().add(canvas1);
        canvas1.setBackground(Color.RED);
        frame1.pack();
        frame1.setVisible(true);
        frame1.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

    }//GEN-LAST:event_btnJuego1ActionPerformed

    private void btnJuego2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJuego2ActionPerformed
        JFrame frame2 = new JFrame("RompeCabezas Internet of Things");
        Tablero canvas2 = new Tablero();
        canvas2.addFigura(new Pieza(840, 14, "/juego2/iot.png"));
        canvas2.addFigura(new Pieza(119, 437, "/juego2/iot1.png"));
        canvas2.addFigura(new Pieza(227, 544, "/juego2/iot2.png"));
        canvas2.addFigura(new Pieza(121, 544, "/juego2/iot3.png"));
        canvas2.addFigura(new Pieza(223, 14, "/juego2/iot4.png"));
        canvas2.addFigura(new Pieza(119, 330, "/juego2/iot5.png"));
        canvas2.addFigura(new Pieza(11, 310, "/juego2/iot6.png"));
        canvas2.addFigura(new Pieza(128, 221, "/juego2/iot7.png"));
        canvas2.addFigura(new Pieza(327, 330, "/juego2/iot8.png"));
        canvas2.addFigura(new Pieza(335, 221, "/juego2/iot9.png"));
        canvas2.addFigura(new Pieza(11, 14, "/juego2/iot10.png"));
        canvas2.addFigura(new Pieza(128, 111, "/juego2/iot11.png"));
        canvas2.addFigura(new Pieza(11, 518, "/juego2/iot12.png"));
        canvas2.addFigura(new Pieza(11, 111, "/juego2/iot13.png"));
        canvas2.addFigura(new Pieza(532, 14, "/juego2/iot14.png"));
        canvas2.addFigura(new Pieza(395, 111, "/juego2/iot15.png"));
        frame2.getContentPane().add(canvas2);
        canvas2.setBackground(Color.GRAY);
        frame2.pack();
        frame2.setVisible(true);
        frame2.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_btnJuego2ActionPerformed

    private void btnJuego3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJuego3ActionPerformed
            JOptionPane.showMessageDialog(null, "EN CONSTRUCCIÓN...", "Implementando...", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnJuego3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuInicio.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MenuInicio().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJuego1;
    private javax.swing.JButton btnJuego2;
    private javax.swing.JButton btnJuego3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblIO;
    // End of variables declaration//GEN-END:variables
}
